<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid Email or Password please try again</name>
   <tag></tag>
   <elementGuidId>eea113c8-d048-403f-b114-e811914c858a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#error-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d02c952-464c-4bd9-b091-9c6843ed618a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-password</value>
      <webElementGuid>f8747022-1915-4b43-8f60-c725a703cab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__input-error w-5/6 text-theme-6 mt-2</value>
      <webElementGuid>6debcf44-edd3-4a46-b467-022bde7f4244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Email or Password please try again. 8 Attempt/s left</value>
      <webElementGuid>b56b4d7c-88f5-4384-80c2-8bd6d976c66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-password&quot;)</value>
      <webElementGuid>1b36ba43-9de9-4012-9a16-87b425852e1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-password']</value>
      <webElementGuid>5e0f757d-2558-476d-9780-fe5c40ecebc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]</value>
      <webElementGuid>737f3be1-164d-4f70-979f-7c59235424e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Greatway Office'])[2]/following::div[3]</value>
      <webElementGuid>81653d3f-dd58-4812-8ea5-1516db1693d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Greatway Office'])[1]/following::div[5]</value>
      <webElementGuid>cbee2796-b7d4-4e68-9641-b382575891bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::div[1]</value>
      <webElementGuid>c8216161-8494-40cd-ad87-428a51240624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[3]</value>
      <webElementGuid>f302b0e1-db7d-48ff-8b65-60427c1d04a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Email or Password please try again. 8 Attempt/s left']/parent::*</value>
      <webElementGuid>a5a6febd-435a-4d8e-aad1-f037f6611ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>0ae303a2-095e-4b8f-9a26-03965b330bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-password' and (text() = 'Invalid Email or Password please try again. 8 Attempt/s left' or . = 'Invalid Email or Password please try again. 8 Attempt/s left')]</value>
      <webElementGuid>e30a9296-8a95-4df9-b858-10af9b297e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
