<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_My Greatway Office_mx-auto</name>
   <tag></tag>
   <elementGuidId>84f894e1-dc06-442a-8b27-1b2eda1a44b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='My Greatway Office']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad6104a2-a1bf-402d-8fa9-8cf03ad8ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>My Greatway Office</value>
      <webElementGuid>1051a75a-653e-412b-a1d8-5e01a012a2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>18945a1a-38c3-43a1-813f-cb33748da471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mgo-stg.greatway.tools/dist/images/Greatway-Logo-Main2.png</value>
      <webElementGuid>2c5b0c31-df4e-4cd8-8875-8688c266a7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-2&quot;]/div[@class=&quot;container sm:px-10&quot;]/div[@class=&quot;block xl:grid grid-cols-2 gap-4&quot;]/div[@class=&quot;h-screen xl:h-auto flex p-5 xl:py-0&quot;]/div[@class=&quot;my-auto mx-auto align-center xl:ml-20 bg-white dark:bg-dark-1 xl:bg-white border-2 border-indigo-600 px-5 py-8 shadow-lg w-full sm:mx-2 sm:w-3/4 lg:w-2/4 xl:w-auto&quot;]/img[@class=&quot;mx-auto&quot;]</value>
      <webElementGuid>2df11029-e87a-484d-acd2-a9ef13d0bde0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='My Greatway Office']</value>
      <webElementGuid>26a88f55-ea56-4165-ae49-e1d2568c0e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d711ebfc-d068-4e54-a6c0-166397c68396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'My Greatway Office' and @src = 'https://mgo-stg.greatway.tools/dist/images/Greatway-Logo-Main2.png']</value>
      <webElementGuid>b065c073-acf1-4dff-a44f-309bc8bfa1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
