<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>171aa980-a1fe-443d-a1fc-4e1e30b62739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Cancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-greatway.py-3.px-4.w-auto.align-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d02ff9dd-3c35-433c-8ebb-ffc8428901b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mgo-stg.greatway.tools/login</value>
      <webElementGuid>2bf42134-ca7c-4d2d-a2bd-b28d4d02ddfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-greatway py-3 px-4 w-auto align-top</value>
      <webElementGuid>40ad0aa2-7953-4fd7-b558-87ae925d4334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Cancel
                        </value>
      <webElementGuid>41d42f0e-dbf9-417d-a54a-e0768ff8b01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-2&quot;]/div[@class=&quot;container sm:px-10 mx-auto&quot;]/div[@class=&quot;block xl:grid grid-cols-2 gap-4 mx-auto&quot;]/div[@class=&quot;h-screen xl:h-auto flex p-5 xl:py-0&quot;]/div[@class=&quot;my-auto mx-auto align-center xl:ml-20 bg-white dark:bg-dark-1 xl:bg-white border-2 border-indigo-600 px-5 py-8 shadow-lg w-full sm:mx-2 sm:w-3/4 lg:w-2/4 xl:w-auto&quot;]/div[@class=&quot;intro-x mt-5 xl:mt-8 text-right&quot;]/a[@class=&quot;btn btn-greatway py-3 px-4 w-auto align-top&quot;]</value>
      <webElementGuid>1c2dba8f-58ae-4f4a-a25b-7e626036d871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>ad215f43-c067-4ee5-9161-88e9ad20fedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Greatway Office'])[1]/following::a[2]</value>
      <webElementGuid>64743bb0-64e7-4524-97be-c3aeb0fe45e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your business any timeyou want anywhere you want.'])[1]/following::a[2]</value>
      <webElementGuid>8290e481-531a-44a3-ac8a-66258f8e0c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Password Reset Link'])[1]/preceding::a[1]</value>
      <webElementGuid>78abbfd6-86c8-4291-9290-46596c70cde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>7bde6f7f-f48d-415e-b45c-651c50ec853f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>5e0c1cd1-4a28-4784-b9f8-1125fbbf955f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mgo-stg.greatway.tools/login')]</value>
      <webElementGuid>b5b3177c-05e6-45f1-b194-26ea1357ec8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>ea8e1bce-4eff-4ca6-8f86-c80eca5b891b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mgo-stg.greatway.tools/login' and (text() = '
                            Cancel
                        ' or . = '
                            Cancel
                        ')]</value>
      <webElementGuid>6932d7b0-2226-4d3b-81af-efb856de391f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
