<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change Password</name>
   <tag></tag>
   <elementGuidId>a56be760-4567-4429-9faa-c24a82ee2ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_o2nh1utf6']/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04dc8a9c-0ab7-4ce2-be7d-0635170760db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/my-profile?cp=true</value>
      <webElementGuid>6ad600dd-f9a4-4328-8ee2-dcefc2de5f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>66f66bb4-5616-4648-8ad2-172bffeccf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#change-password</value>
      <webElementGuid>ac8fe7ae-00e1-499e-9ba9-813303328880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md</value>
      <webElementGuid>92426c08-6a9c-4c36-8266-66e3099eff5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Change Password
                    </value>
      <webElementGuid>3212dbbc-4b87-4052-beb0-daba2a82965e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o2nh1utf6&quot;)/div[@class=&quot;dropdown-menu__content box bg-white dark:bg-dark-6 text-black&quot;]/div[@class=&quot;p-2&quot;]/a[@class=&quot;flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md&quot;]</value>
      <webElementGuid>329ad526-bf69-46d6-ab27-9b0570ab0dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o2nh1utf6']/div/div[2]/a[2]</value>
      <webElementGuid>b5bcd0ad-d60e-4ecb-bbe1-b892b69620ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan Carlo Karingal'])[1]/following::a[2]</value>
      <webElementGuid>b6802e4b-2aab-498a-a985-cf684be09c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change Password']/parent::*</value>
      <webElementGuid>7961d0f6-3c92-4000-a878-7c9c1cf39bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/my-profile?cp=true')]</value>
      <webElementGuid>77a00c56-2787-44e6-bd90-97267b6040cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/a[2]</value>
      <webElementGuid>04610c0c-575e-4d0d-8974-91cddfcc00ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/my-profile?cp=true' and (text() = '
                         Change Password
                    ' or . = '
                         Change Password
                    ')]</value>
      <webElementGuid>89475759-9723-4d2e-a981-0876e15d9c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
