<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help</name>
   <tag></tag>
   <elementGuidId>1fdf3a1f-add2-4c03-b5f2-da39ddcacbd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_o2nh1utf6']/div/div[2]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a70b596b-c8d4-4c22-bef6-56203240604c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mgo_help</value>
      <webElementGuid>be3c146d-9e32-44a6-8da9-3f4149780a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md</value>
      <webElementGuid>b8e7c35f-14bb-444b-8213-2151ea72448a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Help
                    </value>
      <webElementGuid>07c1a504-b301-4fd3-8aef-2659ad67c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o2nh1utf6&quot;)/div[@class=&quot;dropdown-menu__content box bg-white dark:bg-dark-6 text-black&quot;]/div[@class=&quot;p-2&quot;]/a[@class=&quot;flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md&quot;]</value>
      <webElementGuid>600051bd-1ad5-41e2-a5bd-f6c58fa0616b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o2nh1utf6']/div/div[2]/a[3]</value>
      <webElementGuid>8334e500-cb50-4799-9d2b-8a79f1e1326b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help']/parent::*</value>
      <webElementGuid>234cc769-3a5e-445b-8f32-5c3c0cc9769c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mgo_help')]</value>
      <webElementGuid>84d0c5cd-a761-4ee6-a351-79cf0f280848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/a[3]</value>
      <webElementGuid>0380e6af-5067-40ed-b65e-38af5d617d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mgo_help' and (text() = '
                         Help
                    ' or . = '
                         Help
                    ')]</value>
      <webElementGuid>b8c14372-130a-42a5-9bd7-d80d62589416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
