<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>2ce39783-b307-49c6-ab6b-a932f7703754</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_o2nh1utf6']/div/div[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/logout' and (text() = '
                         Logout
                    ' or . = '
                         Logout
                    ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4b09abe-1fea-418c-a625-d37666c786ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout</value>
      <webElementGuid>a131dbb1-011b-4518-9705-62ac90360a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md</value>
      <webElementGuid>53b97764-0574-41f2-9d54-55d762a8b8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Logout
                    </value>
      <webElementGuid>a47d6fc5-b3fa-43a9-a015-f376fbaaedf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o2nh1utf6&quot;)/div[@class=&quot;dropdown-menu__content box bg-white dark:bg-dark-6 text-black&quot;]/div[@class=&quot;p-2 border-t border-black dark:border-dark-3&quot;]/a[@class=&quot;flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-42 dark:hover:bg-dark-3 rounded-md&quot;]</value>
      <webElementGuid>bc224044-2cb7-4fc7-9047-52944f547357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o2nh1utf6']/div/div[3]/a</value>
      <webElementGuid>ef598013-6091-4aef-9204-9ca333d44ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>cfa08454-2985-464e-ae43-67269876aa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout')]</value>
      <webElementGuid>151deb64-ba91-4aaa-85a2-ebea56d831ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/a</value>
      <webElementGuid>b35afb49-7206-481e-a73b-2118e1bd4ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/logout' and (text() = '
                         Logout
                    ' or . = '
                         Logout
                    ')]</value>
      <webElementGuid>9d9c33bb-f64c-4d92-84fb-c71df860a1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
