<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_user_LHIA</name>
   <tag></tag>
   <elementGuidId>621e03c9-e49f-43db-af7f-20d38e619185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_o2nh1utf6']/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Life Health Insurance Agent Supervisor' or . = 'Life Health Insurance Agent Supervisor')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>99ab0612-6ac9-4ad7-97cc-6c35cb1ff201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs text-black mt-0.5 dark:text-gray-600</value>
      <webElementGuid>01e60c6a-803c-497c-9970-7ebbba81d615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Life Health Insurance Agent Supervisor</value>
      <webElementGuid>b8ca6262-5ca5-4d26-b216-300e81a88ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o2nh1utf6&quot;)/div[@class=&quot;dropdown-menu__content box bg-white dark:bg-dark-6 text-black&quot;]/div[@class=&quot;p-4 border-b border-gray-800 dark:border-dark-3&quot;]/p[@class=&quot;text-xs text-black mt-0.5 dark:text-gray-600&quot;]</value>
      <webElementGuid>3bc7998e-1c6c-428c-9f5b-23826fdf7774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o2nh1utf6']/div/div/p</value>
      <webElementGuid>23c4a8e5-9816-4f53-917c-13d18a2580dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan Carlo Karingal'])[1]/following::p[1]</value>
      <webElementGuid>c64d920d-c021-4bd5-9053-3e3be4af7773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      <webElementGuid>17c61a50-f2e8-43ce-9363-43f5fcf1800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agent-Supervisor (Pilot)']/parent::*</value>
      <webElementGuid>cd2111c4-92d2-441f-9c69-8259a9cb5e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/p</value>
      <webElementGuid>baa641a8-f566-4f9b-98e7-ee9fe48e4c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Agent-Supervisor (Pilot)' or . = 'Agent-Supervisor (Pilot)')]</value>
      <webElementGuid>a09d0f39-5830-4900-bb7c-e8c30cfd7860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
