<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_user_OA</name>
   <tag></tag>
   <elementGuidId>61044de4-d508-47a2-bb9e-d685c7035049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_o2nh1utf6']/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Office Admin' or . = 'Office Admin')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e4197929-ce29-44b7-97c1-90b6a4b600c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs text-black mt-0.5 dark:text-gray-600</value>
      <webElementGuid>76db7bb3-dc3c-4fc2-bd89-bed494796c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office Admin</value>
      <webElementGuid>dcd8fa52-e34c-47b4-872d-59af3d429ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o2nh1utf6&quot;)/div[@class=&quot;dropdown-menu__content box bg-white dark:bg-dark-6 text-black&quot;]/div[@class=&quot;p-4 border-b border-gray-800 dark:border-dark-3&quot;]/p[@class=&quot;text-xs text-black mt-0.5 dark:text-gray-600&quot;]</value>
      <webElementGuid>a06c4632-b2dd-4f0d-a9b3-5ea1fbf12781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o2nh1utf6']/div/div/p</value>
      <webElementGuid>8de9dd97-7251-418a-8c17-051fb62e3038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan Carlo Karingal'])[1]/following::p[1]</value>
      <webElementGuid>040d9db6-78a6-4d77-9bc3-b877d8b1c0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      <webElementGuid>f2c31d96-51d3-4259-a5ea-fcc770420305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agent-Supervisor (Pilot)']/parent::*</value>
      <webElementGuid>d92acbc5-f2d8-4e6d-b5f8-8b3792b8d7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/p</value>
      <webElementGuid>7d69da2a-0266-4d09-ac8d-5ea70d663a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Agent-Supervisor (Pilot)' or . = 'Agent-Supervisor (Pilot)')]</value>
      <webElementGuid>f387957c-dda3-48e7-8e0c-362500280e25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
